dist: trusty
sudo: required
language: ruby
rvm:
- 2.3.1
before_install:
- gem install bundler -v 1.16.6
- sudo apt-get update -qq
- wget https://github.com/jgm/pandoc/releases/download/2.3.1/pandoc-2.3.1-1-amd64.deb && sudo dpkg -i pandoc-*.deb
