dist: trusty
sudo: required
language: ruby
rvm:
- 2.3.1
before_install:
- gem install bundler -v 1.13.2
- sudo apt-get update -qq
- wget https://github.com/jgm/pandoc/releases/download/1.19.1/pandoc-1.19.1-1-amd64.deb && sudo dpkg -i pandoc-1.19.1-1-amd64.deb

